# Generated by Django 4.0.5 on 2022-07-12 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('max_weight', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MusclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrainUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('weight', models.FloatField()),
                ('level_weight_increase', models.FloatField(default=0)),
                ('current_level', models.IntegerField(default=0)),
                ('reps', models.JSONField()),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cycle', models.IntegerField(default=None, null=True)),
            ],
            options={
                'unique_together': {('name', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='TrainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainplan')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainunit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.JSONField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainhistory')),
                ('train_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainunit')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muslce_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.musclepart'),
        ),
    ]
