# Generated by Django 4.0.6 on 2022-07-14 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_trainhistory_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanUnit',
            new_name='PlanModule',
        ),
        migrations.RenameModel(
            old_name='TrainUnit',
            new_name='TrainModule',
        ),
    ]
