# Generated by Django 4.0.6 on 2022-07-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_trainmodule_progress_trainplan_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planmodule',
            old_name='unit',
            new_name='module',
        ),
    ]
