# Generated by Django 4.0.6 on 2022-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_unit_planmodule_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainmodule',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
