# Generated by Django 4.0.6 on 2022-07-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_trainmodule_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainmodule',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='trainmodule',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
