# Generated by Django 4.1 on 2022-08-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_trainmodule_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trainplan",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="trainplan",
            name="cycle",
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
