# Generated by Django 4.1 on 2022-09-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_trainplan_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="planmodule",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
