# Generated by Django 4.1 on 2022-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_planmodule_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planmodule",
            unique_together={("plan", "module")},
        ),
        migrations.AddField(
            model_name="planmodule",
            name="order_in_plan",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="planmodule",
            unique_together={("plan", "module"), ("plan", "order_in_plan")},
        ),
    ]
