# Generated by Django 4.0.5 on 2022-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='max_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wieght',
            field=models.FloatField(default=0),
        ),
    ]
