# Generated by Django 4.1 on 2022-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_current_cycle_user_max_cycle_user_wieght"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
