# Generated by Django 4.1 on 2022-09-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_trainplan_cycle"),
        ("users", "0003_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_train",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_plan",
                to="app.trainplan",
            ),
        ),
    ]
