# Generated by Django 4.1 on 2022-09-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_planmodule_done"),
        ("users", "0004_user_current_train"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_train",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_train",
                to="app.trainplan",
            ),
        ),
    ]
